using System;

class Except
{
    public static void Throw()
    {
        throw new System.IO.IOException("Something Happened");
    }
}
